#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr  4 16:37:06 2024

@author: torycat
Modified Code from Book
"""

import matplotlib.pyplot as plot
import numpy as nump
import pandas as pand
from sklearn.linear_model import Perceptron

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

df = pand.read_csv(url, sep=',', encoding='utf-8')

# df.tail()
print(df.tail())


# select setosa and versicolor

y = df.iloc[0:100, 4].values

y = nump.where(y == 'Iris-setosa', 0, 1)

# extract sepal length and petal length

X = df.iloc[0:100, [0, 2]].values

# plot data

plot.scatter(X[:50, 0], X[:50, 1], color='red', marker='o', label='Setosa')

plot.scatter(X[50:100, 0], X[50:100, 1], color='blue', marker='s', label='Versicolor')

plot.xlabel('Sepal length [cm]')
plot.ylabel('Petal length [cm]')

plot.legend(loc='upper left')
plot.show()

# Learning?

ppn = Perceptron(eta0=0.1, max_iter=10)
ppn.fit(X, y)
plot.plot(range(1, len(ppn.errors_) + 1), ppn.errors_, marker='o')
plot.xlabel('Epochs')
plot.ylabel('Number of updates')
plot.show()
